#!/usr/bin/env python3
"""DSP clap calibration — find best thresholds from live mic.

Test sequence:
1. 10 seconds silence (baseline noise floor)
2. 5 speech samples (rejection baseline)
3. 5 single claps (detection check)
4. 5 double claps (success target)

Logs per-frame features and recommends env config.
"""

import argparse
import json
import math
import os
import struct
import sys
import time

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


SAMPLE_RATE = 16000
FRAME_SAMPLES = int(SAMPLE_RATE * 80 / 1000)
ARTIFACTS_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "artifacts")


def record_stream(duration_sec: float, device: int | None):
    import sounddevice as sd
    frames = int(SAMPLE_RATE * duration_sec / FRAME_SAMPLES)
    audio = []
    stream = sd.InputStream(device=device, channels=1, samplerate=SAMPLE_RATE, dtype=np.int16)
    with stream:
        for _ in range(frames):
            chunk, _ = stream.read(FRAME_SAMPLES)
            audio.append(chunk.copy())
    return np.concatenate(audio) if audio else np.array([], dtype=np.int16)


def compute_features(pcm16: bytes):
    n = len(pcm16) // 2
    if n <= 0:
        return None
    samples = struct.unpack(f"<{n}h", pcm16)
    sum_sq = 0
    peak = 0
    hf_energy = 0.0
    total_energy = 0.0
    for i, s in enumerate(samples):
        sq = s * s
        sum_sq += sq
        abs_s = abs(s)
        if abs_s > peak:
            peak = abs_s
        hf_freq = (i / n) * (SAMPLE_RATE / 2) if i > 0 else 0
        if hf_freq >= 3000:
            hf_energy += sq
        total_energy += sq
    rms = (sum_sq / n) ** 0.5 / 32768.0
    peak_norm = peak / 32768.0
    avg = rms
    peak_ratio = peak_norm / avg if avg > 1e-10 else 0.0
    hf_ratio = hf_energy / total_energy if total_energy > 0 else 0.0
    duration_ms = (n / SAMPLE_RATE) * 1000.0
    return {
        "rms": rms,
        "peak": peak_norm,
        "peak_ratio": peak_ratio,
        "hf_ratio": hf_ratio,
        "duration_ms": duration_ms,
        "n": n,
    }


def test_thresholds(features_list: list[dict], rms_t: float, peak_t: float,
                    pr_t: float, hf_t: float, cooldown_ms: float) -> int:
    """Count clap detections with given thresholds (no cooldown between batches)."""
    count = 0
    for f in features_list:
        if f is None:
            continue
        if f["duration_ms"] > 200:
            continue
        if f["rms"] < rms_t:
            continue
        if f["peak"] < peak_t:
            continue
        if f["peak_ratio"] < pr_t:
            continue
        if f["hf_ratio"] < hf_t:
            continue
        count += 1
    return count


def write_calibration_artifacts(recommended: dict, summary: dict) -> dict:
    os.makedirs(ARTIFACTS_DIR, exist_ok=True)
    env_path = os.path.join(ARTIFACTS_DIR, "dsp_clap_recommended_env.ps1")
    json_path = os.path.join(ARTIFACTS_DIR, "dsp_clap_calibration_summary.json")
    with open(env_path, "w", encoding="utf-8") as f:
        f.write("# Generated by scripts/debug_dsp_clap_calibration.py\n")
        for key, value in recommended.items():
            if isinstance(value, float):
                f.write(f"$env:{key}=\"{value:.4f}\"\n")
            else:
                f.write(f"$env:{key}=\"{value}\"\n")
    payload = {"recommended": recommended, "summary": summary}
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, sort_keys=True)
    return {"env_path": env_path, "json_path": json_path}


def main():
    parser = argparse.ArgumentParser(description="DSP clap calibration tool")
    parser.add_argument("--device", type=int, default=None)
    args = parser.parse_args()

    print("=" * 60)
    print("DSP CLAP CALIBRATION")
    print("=" * 60)
    print()

    silence_features: list[dict] = []
    speech_features: list[dict] = []
    single_clap_features: list[dict] = []
    double_clap_features: list[dict] = []

    # Phase 1: Silence
    print("[1] Silence 10 seconds (stay quiet)...")
    time.sleep(0.5)
    audio = record_stream(10.0, args.device)
    for offset in range(0, len(audio) - FRAME_SAMPLES + 1, FRAME_SAMPLES):
        chunk = audio[offset:offset + FRAME_SAMPLES]
        f = compute_features(chunk.tobytes())
        if f:
            silence_features.append(f)
    print(f"  recorded {len(silence_features)} silence frames")
    print(f"  max_rms={max(f['rms'] for f in silence_features):.5f} "
          f"max_peak={max(f['peak'] for f in silence_features):.4f} "
          f"max_peak_ratio={max(f['peak_ratio'] for f in silence_features):.2f}")
    print()

    # Phase 2: Speech
    print("[2] Say 5 short phrases (press Enter between each)")
    for i in range(5):
        input(f"  [{i+1}/5] Press Enter and speak a short phrase...")
        time.sleep(0.3)
        audio = record_stream(2.0, args.device)
        for offset in range(0, len(audio) - FRAME_SAMPLES + 1, FRAME_SAMPLES):
            chunk = audio[offset:offset + FRAME_SAMPLES]
            f = compute_features(chunk.tobytes())
            if f:
                speech_features.append(f)
    print(f"  recorded {len(speech_features)} speech frames")
    print()

    # Phase 3: Single claps
    print("[3] Single clap 5 times (press Enter between each)")
    for i in range(5):
        input(f"  [{i+1}/5] Press Enter and clap once...")
        time.sleep(0.3)
        audio = record_stream(1.0, args.device)
        for offset in range(0, len(audio) - FRAME_SAMPLES + 1, FRAME_SAMPLES):
            chunk = audio[offset:offset + FRAME_SAMPLES]
            f = compute_features(chunk.tobytes())
            if f:
                single_clap_features.append(f)
    print(f"  recorded {len(single_clap_features)} single clap frames")
    print()

    # Phase 4: Double claps
    print("[4] Double clap 5 times (press Enter between each)")
    for i in range(5):
        input(f"  [{i+1}/5] Press Enter and clap twice...")
        time.sleep(0.3)
        audio = record_stream(1.5, args.device)
        for offset in range(0, len(audio) - FRAME_SAMPLES + 1, FRAME_SAMPLES):
            chunk = audio[offset:offset + FRAME_SAMPLES]
            f = compute_features(chunk.tobytes())
            if f:
                double_clap_features.append(f)
    print(f"  recorded {len(double_clap_features)} double clap frames")
    print()

    # Log per-frame features
    print("=" * 60)
    print("SILENCE FRAME FEATURES (first 20)")
    print("  rms,peak,peak_ratio,hf_ratio,duration_ms")
    for f in silence_features[:20]:
        print(f"  {f['rms']:.5f},{f['peak']:.4f},{f['peak_ratio']:.2f},"
              f"{f['hf_ratio']:.3f},{f['duration_ms']:.0f}")
    print()

    print("SINGLE CLAP FRAME FEATURES (peak frames)")
    for f in sorted(single_clap_features, key=lambda x: -x['peak'])[:10]:
        print(f"  rms={f['rms']:.5f} peak={f['peak']:.4f} "
              f"peak_ratio={f['peak_ratio']:.2f} hf_ratio={f['hf_ratio']:.3f} "
              f"dur={f['duration_ms']:.0f}ms")
    print()

    print("DOUBLE CLAP FRAME FEATURES (peak frames)")
    for f in sorted(double_clap_features, key=lambda x: -x['peak'])[:10]:
        print(f"  rms={f['rms']:.5f} peak={f['peak']:.4f} "
              f"peak_ratio={f['peak_ratio']:.2f} hf_ratio={f['hf_ratio']:.3f} "
              f"dur={f['duration_ms']:.0f}ms")
    print()

    # Compute statistics for recommended thresholds
    silence_max_rms = max(f['rms'] for f in silence_features) if silence_features else 0.01
    silence_max_peak = max(f['peak'] for f in silence_features) if silence_features else 0.01
    silence_max_pr = max(f['peak_ratio'] for f in silence_features) if silence_features else 1.0
    silence_max_hf = max(f['hf_ratio'] for f in silence_features) if silence_features else 0.1

    speech_max_rms = max(f['rms'] for f in speech_features) if speech_features else 0.01
    speech_max_pr = max(f['peak_ratio'] for f in speech_features) if speech_features else 2.0

    clap_min_peak = min(f['peak'] for f in single_clap_features + double_clap_features) if (single_clap_features + double_clap_features) else 0.5
    clap_min_pr = min(f['peak_ratio'] for f in single_clap_features + double_clap_features) if (single_clap_features + double_clap_features) else 4.0
    clap_min_hf = min(f['hf_ratio'] for f in single_clap_features + double_clap_features) if (single_clap_features + double_clap_features) else 0.3

    recommended = {
        "NEXI_DSP_CLAP_RMS_THRESHOLD": max(silence_max_rms * 2.5, 0.03),
        "NEXI_DSP_CLAP_PEAK_THRESHOLD": max(silence_max_peak * 2.0, clap_min_peak * 0.6),
        "NEXI_DSP_CLAP_PEAK_RATIO": max(silence_max_pr * 1.5, clap_min_pr * 0.7),
        "NEXI_DSP_CLAP_HF_RATIO": max(silence_max_hf * 1.5, clap_min_hf * 0.7),
        "NEXI_DSP_CLAP_EVENT_COOLDOWN_MS": 80,
        "NEXI_DSP_CLAP_SPEECH_REJECT_MS": 250,
        "NEXI_CLAP_MIN_GAP_MS": 100,
        "NEXI_CLAP_MAX_GAP_MS": 3500,
    }

    # Validate recommended thresholds
    n_silence_claps = test_thresholds(
        silence_features,
        recommended["NEXI_DSP_CLAP_RMS_THRESHOLD"],
        recommended["NEXI_DSP_CLAP_PEAK_THRESHOLD"],
        recommended["NEXI_DSP_CLAP_PEAK_RATIO"],
        recommended["NEXI_DSP_CLAP_HF_RATIO"],
        recommended["NEXI_DSP_CLAP_EVENT_COOLDOWN_MS"],
    )
    n_speech_claps = test_thresholds(
        speech_features,
        recommended["NEXI_DSP_CLAP_RMS_THRESHOLD"],
        recommended["NEXI_DSP_CLAP_PEAK_THRESHOLD"],
        recommended["NEXI_DSP_CLAP_PEAK_RATIO"],
        recommended["NEXI_DSP_CLAP_HF_RATIO"],
        recommended["NEXI_DSP_CLAP_EVENT_COOLDOWN_MS"],
    )
    n_single_detected = test_thresholds(
        single_clap_features,
        recommended["NEXI_DSP_CLAP_RMS_THRESHOLD"],
        recommended["NEXI_DSP_CLAP_PEAK_THRESHOLD"],
        recommended["NEXI_DSP_CLAP_PEAK_RATIO"],
        recommended["NEXI_DSP_CLAP_HF_RATIO"],
        recommended["NEXI_DSP_CLAP_EVENT_COOLDOWN_MS"],
    )
    n_double_detected = test_thresholds(
        double_clap_features,
        recommended["NEXI_DSP_CLAP_RMS_THRESHOLD"],
        recommended["NEXI_DSP_CLAP_PEAK_THRESHOLD"],
        recommended["NEXI_DSP_CLAP_PEAK_RATIO"],
        recommended["NEXI_DSP_CLAP_HF_RATIO"],
        recommended["NEXI_DSP_CLAP_EVENT_COOLDOWN_MS"],
    )

    print("=" * 60)
    print("RECOMMENDED ENV:")
    print("=" * 60)
    for key, val in recommended.items():
        if isinstance(val, float):
            print(f"  {key}={val:.4f}")
        else:
            print(f"  {key}={val}")
    print()

    print(f"Expected silence false claps: {n_silence_claps} (target: 0)")
    print(f"Expected speech false claps: {n_speech_claps} (target: 0)")
    print(f"Single clap frames detected: {n_single_detected} (target: >=1)")
    print(f"Double clap frames detected: {n_double_detected} (target: >=2)")
    print()

    passes = 0
    if n_silence_claps == 0:
        print("  PASS silence false clap = 0")
        passes += 1
    else:
        print(f"  FAIL silence false clap = {n_silence_claps}")
    if n_speech_claps == 0:
        print("  PASS speech false clap = 0")
        passes += 1
    else:
        print(f"  FAIL speech false clap = {n_speech_claps}")
    if n_single_detected >= 1:
        print("  PASS single clap detected >= 1")
        passes += 1
    else:
        print("  FAIL single clap detected = 0")
    if n_double_detected >= 2:
        print("  PASS double clap frames >= 2")
        passes += 1
    else:
        print(f"  FAIL double clap frames = {n_double_detected} (may need relaxed thresholds)")

    print()
    if passes == 4:
        print("CALIBRATION: RECOMMENDED THRESHOLDS READY")
    else:
        print(f"CALIBRATION: PARTIAL ({passes}/4) — manual tuning may be needed")

    summary = {
        "silence_false_claps": n_silence_claps,
        "speech_false_claps": n_speech_claps,
        "single_clap_frames_detected": n_single_detected,
        "double_clap_frames_detected": n_double_detected,
        "passes": passes,
        "total_checks": 4,
    }
    paths = write_calibration_artifacts(recommended, summary)
    print(f"[ARTIFACT] env={paths['env_path']}")
    print(f"[ARTIFACT] summary={paths['json_path']}")


if __name__ == "__main__":
    main()
